{
 "title": "Docker Prometheus Monitoring Copy",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
   },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "CPU Name",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  { "title": "Host Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Targets Online",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance) * 100) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg( node_filesystem_avail_bytes {mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(sum(node_memory_MemTotal_bytes) by (instance) - sum(node_memory_MemAvailable_bytes) by (instance)) / sum(node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "Used-{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg( node_filesystem_avail_bytes {mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id,name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{image!=\"\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Network Input",
     "type": "graph",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Network Output",
     "type": "graph",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  }
 ]
}